#pragma once

enum MapLayerNames {
	MLN_NULL_LAYER = -1,
	MLN_FIRST_LAYER,
	MLN_SECOND_LAYER,
	MLN_THIRD_LAYER_OVER_PLAYER,
	MLN_COLLISION_LAYER,
	MLN_ENEMY_SPAWNER_LAYER,
	MLN_COUNTS
};

enum MapObjectLayerNames {
	MOLN_ENEMY_SPAWNER_LAYER,
	MOLN_COUNTS
};