#pragma once

enum PlayerAnimationSet {
	PAS_IDLE,
	PAS_WALK,
	PAS_AFTER_RUN_STOP,
	PAS_JUMPUP,
	PAS_FALLING,
	PAS_JUMPFORWARD,
	PAS_FALLINGFORWARD,
	PAS_SHOOTING_IDLE,
	PAS_SHOOTING_WALKING,
	PAS_SHOOTING_JUMPING,
	PAS_COUNTS
};