#pragma once

enum PlayerAnimationSet {
	PAS_IDLE,
	PAS_WALK,
	PAS_AFTER_RUN_STOP,
	PAS_CROUCH_IDLE,
	PAS_CROUCH_WALKING,
	PAS_JUMP_UP,
	PAS_JUMP_FORWARD,
	PAS_FALLING,
	PAS_FALLING_FORWARD,
	PAS_SHOOTING_IDLE,
	PAS_SHOOTING_IDLE_UP,
	PAS_SHOOTING_WALK,
	PAS_SHOOTING_WALK_UP,
	PAS_SHOOTING_CROUCH,
	PAS_SHOOTING_JUMP_UP,
	PAS_SHOOTING_UP_JUMP_UP,
	PAS_MELEE_ATTACK,
	PAS_SHOOTING_JUMP_FORWARD,
	PAS_SHOOTING_JUMP_DOWN,
	PAS_COUNTS
};
