#pragma once

enum ResourceIDFrames {
	// This enum just exist because we cant fuck use the hash maps. so yeah, you take it
	// keep track of the frames of the sprite
	IDF_NULL = -1,
	IDF_PLAYER_IDLE_BODY = 4,
	IDF_PLAYER_IDLE_LEGS = 1,
	IDF_PLAYER_WALK_BODY = 12,
	IDF_PLAYER_WALK_LEGS = 12,
	IDF_PLAYER_AFTER_RUN_STOP_F = 4,
	IDF_PLAYER_CROUCH_IDLE_F = 4,
	IDF_PLAYER_CROUCH_WALKING_F = 7,
	IDF_PLAYER_JUMPUP_BODY = 6,
	IDF_PLAYER_JUMPUP_LEGS = 6,
	IDF_PLAYER_FALLING_BODY = 1,
	IDF_PLAYER_FALLING_LEGS = 1,
	IDF_PLAYER_JUMPFORWARD_BODY = 6,
	IDF_PLAYER_JUMPFORWARD_LEGS = 6,
	IDF_PLAYER_FALLINGFORWARD_BODY = 1,
	IDF_PLAYER_FALLINGFORWARD_LEGS = 1,
	IDF_PLAYER_SHOOTING_BODY = 10,
	IDF_BULLET_PISTOL = 1,
	IDF_MAP_TILESET = 1,
	IDF_COLLISION_TILESET = 1
};