#pragma once

enum ResourceID {
	//dave feeedback to change the null to 0 and set a invalid sprite or smth, 
	// because indexing in -1 is gonna make the game crash
	ID_NULL = -1,
	ID_PLAYER_IDLE_BODY,
	ID_PLAYER_IDLE_LEGS,
	ID_PLAYER_WALK_BODY,
	ID_PLAYER_WALK_LEGS,
	ID_PLAYER_AFTER_RUN_STOP_F, //F stay for full body
	ID_PLAYER_CROUCH_IDLE_F,
	ID_PLAYER_CROUCH_WALKING_F,
	ID_PLAYER_JUMPUP_BODY,
	ID_PLAYER_JUMPUP_LEGS,
	ID_PLAYER_FALLING_BODY,
	ID_PLAYER_FALLING_LEGS,
	ID_PLAYER_JUMPFORWARD_BODY,
	ID_PLAYER_JUMPFORWARD_LEGS,
	ID_PLAYER_FALLINGFORWARD_BODY,
	ID_PLAYER_FALLINGFORWARD_LEGS,
	ID_PLAYER_SHOOTING_BODY,
	ID_PLAYER_SHOOTING_UP_BODY,
	ID_PLAYER_SHOOTING_CROUCH_F,
	ID_REBELSOLDIER_IDLE,
	ID_REBELSOLDIER_WALK,
	ID_REBELSOLDIER_STOP,
	ID_REBELSOLDIER_JUMP_UP,
	ID_REBELSOLDIER_JUMP_FORWARD,
	ID_REBELSOLDIER_SCARED,
	ID_REBELSOLDIER_FALLING,
	ID_REBELSOLDIER_COVER,
	ID_BULLET_PISTOL,
	ID_MAP_TILESET,
	ID_COLLISION_TILESET,
	ID_COUNTS
};